GPU: '1'
b1: 0.5
b2: 0.999
batch_size: 8
datasets_path: /dataB/wangbo/CSU_Data/20250626_OC4&BRD4-Halo_liveSR/OCT4_BRD4_liveSR
fmap: 16
gap_t: 5
gap_x: 93
gap_y: 93
lr: 5.0e-05
masking_ratio: 0.05
n_epochs: 10
neighbor_radius_xy: 3
neighbot_radius_t: 0
output_dir: ./results
overlap_factor: 0.25
patch_t: 8
patch_x: 125
patch_y: 125
pth_path: ./pth/OCT4_BRD4_liveSR_202508141924
scale_factor: 1
select_img_num: 100000
train_datasets_size: 6000
